baseurl = "http://miraglobal.com/"
languageCode = "en-us"
theme = "sam"
title = "miraglobal"
[params]
clickablephotos = true
dateform = "Monday 2nd January 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "About Open Source and Education"
favicon = "/sam.ico"
footertext = "This is a fast static site"
galleryfolder = "images/"
homepage = "main"
primaryimage = "/tn.png"
pygmentscodefences = true
pygmentsstyle = "monokai"
twittercard = "summary_large_image"
[[params.mainmenu]]
link = "/posts"
text = "news"
[[params.mainmenu]]
link = "/about"
text = "Contact"
