baseurl = "https://timbuktuvariance.github.io/mg2web/"
languageCode = "en-us"
theme = "sam"
title = "Call me Sam"
[params]
clickablephotos = true
dateform = "Mon Jan 02, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "A new Hugo site."
favicon = "/sam.ico"
footertext = "Call me Sam, a theme for Hugo."
galleryfolder = "images/"
homepage = "main"
primaryimage = "/tn.png"
pygmentscodefences = true
pygmentsstyle = "monokai"
twittercard = "summary_large_image"
[[params.mainmenu]]
link = "/posts"
text = "writing"
[[params.mainmenu]]
link = "/gallery"
text = "gallery"
[[params.mainmenu]]
link = "/about"
text = "who is sam?"
